version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    poetry: "1.7.1"

#python:
# install:
#   - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
