version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    # https://browniebroke.com/blog/specify-docs-dependency-groups-with-poetry-and-read-the-docs/
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies
      - poetry install --with docs
      - pip install mkdocs-material
      - pip install mkdocstrings-python

mkdocs:
  configuration: mkdocs.yml
