site_name: Certified API docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Install: cli.md
  - Tutorials: tutorials.md
  - User Guide:
    - how-to-guides.md
  - Reference:
    - certs.md
    - "Configuration / Keyfile Layout": keys.md
  - "Concept Guide": explanation.md
